// Mock data for Madhya Pradesh - Academic Verification Portal
export const mockUniversities = [
  {
    id: 1,
    name: "Devi Ahilya Vishwavidyalaya (DAVV)",
    ugcCode: "DAVV001",
    state: "Madhya Pradesh",
    type: "State",
    status: "Active",
    collegeCount: 142,
    studentCount: 385000,
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    name: "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)",
    ugcCode: "RGPV002",
    state: "Madhya Pradesh",
    type: "State",
    status: "Active",
    collegeCount: 198,
    studentCount: 420000,
    createdAt: "2024-02-10",
  },
  {
    id: 3,
    name: "Barkatullah University Bhopal",
    ugcCode: "BUB003",
    state: "Madhya Pradesh",
    type: "State",
    status: "Active",
    collegeCount: 85,
    studentCount: 165000,
    createdAt: "2024-01-20",
  },
  {
    id: 4,
    name: "Jiwaji University Gwalior",
    ugcCode: "JUG004",
    state: "Madhya Pradesh",
    type: "State",
    status: "Active",
    collegeCount: 76,
    studentCount: 142000,
    createdAt: "2024-02-05",
  },
  {
    id: 5,
    name: "Vikram University Ujjain",
    ugcCode: "VUU005",
    state: "Madhya Pradesh",
    type: "State",
    status: "Active",
    collegeCount: 68,
    studentCount: 128000,
    createdAt: "2024-01-25",
  },
  {
    id: 6,
    name: "IIT Indore",
    ugcCode: "IITI006",
    state: "Madhya Pradesh",
    type: "Central",
    status: "Active",
    collegeCount: 1,
    studentCount: 8500,
    createdAt: "2024-01-18",
  },
  {
    id: 7,
    name: "AIIMS Bhopal",
    ugcCode: "AIIMSBPL007",
    state: "Madhya Pradesh",
    type: "Central",
    status: "Active",
    collegeCount: 1,
    studentCount: 1200,
    createdAt: "2024-02-12",
  },
  {
    id: 8,
    name: "IIM Indore",
    ugcCode: "IIMI008",
    state: "Madhya Pradesh",
    type: "Central",
    status: "Active",
    collegeCount: 1,
    studentCount: 950,
    createdAt: "2024-01-22",
  },
];

export const mockInstitutions = [
  {
    id: 1,
    name: "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
    universityId: 2,
    universityName: "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)",
    code: "SGSITS001",
    address: "Indore, Madhya Pradesh",
    contactPerson: "Dr. Ramesh Verma",
    email: "admin@sgsits.ac.in",
    phone: "+91 98765 43210",
    status: "Active",
    studentCount: 2800,
    createdAt: "2024-03-05",
  },
  {
    id: 2,
    name: "Prestige Institute of Management and Research",
    universityId: 1,
    universityName: "Devi Ahilya Vishwavidyalaya (DAVV)",
    code: "PIMR002",
    address: "Indore, Madhya Pradesh",
    contactPerson: "Dr. Anjali Sharma",
    email: "admin@pimr.edu",
    phone: "+91 98765 43211",
    status: "Active",
    studentCount: 1850,
    createdAt: "2024-03-10",
  },
  {
    id: 3,
    name: "Madhav Institute of Technology and Science (MITS)",
    universityId: 2,
    universityName: "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)",
    code: "MITS003",
    address: "Gwalior, Madhya Pradesh",
    contactPerson: "Dr. Suresh Patel",
    email: "admin@mitsgwalior.in",
    phone: "+91 98765 43212",
    status: "Active",
    studentCount: 3200,
    createdAt: "2024-03-12",
  },
  {
    id: 4,
    name: "Government Holkar Science College",
    universityId: 1,
    universityName: "Devi Ahilya Vishwavidyalaya (DAVV)",
    code: "GHSC004",
    address: "Indore, Madhya Pradesh",
    contactPerson: "Dr. Meena Joshi",
    email: "principal@holkarcollege.edu",
    phone: "+91 98765 43213",
    status: "Active",
    studentCount: 2450,
    createdAt: "2024-03-15",
  },
  {
    id: 5,
    name: "Mahakal Institute of Technology",
    universityId: 2,
    universityName: "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)",
    code: "MIT005",
    address: "Ujjain, Madhya Pradesh",
    contactPerson: "Dr. Vikram Singh",
    email: "admin@mitujjain.ac.in",
    phone: "+91 98765 43214",
    status: "Active",
    studentCount: 1980,
    createdAt: "2024-03-18",
  },
  {
    id: 6,
    name: "Lakshmi Narain College of Technology (LNCT)",
    universityId: 2,
    universityName: "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)",
    code: "LNCT006",
    address: "Bhopal, Madhya Pradesh",
    contactPerson: "Dr. Pradeep Gupta",
    email: "director@lnct.ac.in",
    phone: "+91 98765 43215",
    status: "Active",
    studentCount: 4500,
    createdAt: "2024-03-20",
  },
];

export const mockAdmins = [
  {
    id: 1,
    name: "Ramesh Kumar Verma",
    email: "ramesh.verma@sgsits.ac.in",
    institutionId: 1,
    institutionName:
      "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
    role: "College Admin",
    status: "Active",
    phone: "+91 98270 11111",
    createdAt: "2024-04-01",
    lastLogin: "2024-12-06",
  },
  {
    id: 2,
    name: "Anjali Sharma",
    email: "anjali.sharma@pimr.edu",
    institutionId: 2,
    institutionName: "Prestige Institute of Management and Research",
    role: "College Admin",
    status: "Active",
    phone: "+91 98270 22222",
    createdAt: "2024-04-05",
    lastLogin: "2024-12-07",
  },
  {
    id: 3,
    name: "Suresh Patel",
    email: "suresh.patel@mitsgwalior.in",
    institutionId: 3,
    institutionName: "Madhav Institute of Technology and Science (MITS)",
    role: "College Admin",
    status: "Active",
    phone: "+91 98270 33333",
    createdAt: "2024-04-08",
    lastLogin: "2024-12-06",
  },
  {
    id: 4,
    name: "Meena Joshi",
    email: "meena.joshi@holkarcollege.edu",
    institutionId: 4,
    institutionName: "Government Holkar Science College",
    role: "Data Manager",
    status: "Active",
    phone: "+91 98270 44444",
    createdAt: "2024-04-10",
    lastLogin: "2024-12-07",
  },
  {
    id: 5,
    name: "Vikram Singh Rajput",
    email: "vikram.singh@mitujjain.ac.in",
    institutionId: 5,
    institutionName: "Mahakal Institute of Technology",
    role: "College Admin",
    status: "Active",
    phone: "+91 98270 55555",
    createdAt: "2024-04-12",
    lastLogin: "2024-12-06",
  },
];

export const mockRecruiters = [
  {
    id: 1,
    organizationName: "Infosys Limited",
    contactPerson: "Rajesh Malhotra",
    email: "rajesh.m@infosys.com",
    phone: "+91 98270 66666",
    status: "Active",
    verificationsCount: 1245,
    subscriptionType: "Enterprise",
    createdAt: "2024-05-15",
    lastActive: "2024-12-06",
  },
  {
    id: 2,
    organizationName: "TCS (Tata Consultancy Services)",
    contactPerson: "Priya Deshmukh",
    email: "priya.d@tcs.com",
    phone: "+91 98270 77777",
    status: "Active",
    verificationsCount: 1892,
    subscriptionType: "Enterprise",
    createdAt: "2024-05-20",
    lastActive: "2024-12-07",
  },
  {
    id: 3,
    organizationName: "Wipro Technologies",
    contactPerson: "Anil Gupta",
    email: "anil.gupta@wipro.com",
    phone: "+91 98270 88888",
    status: "Active",
    verificationsCount: 967,
    subscriptionType: "Enterprise",
    createdAt: "2024-05-25",
    lastActive: "2024-12-06",
  },
  {
    id: 4,
    organizationName: "Pithampur Industrial Area HR Consortium",
    contactPerson: "Sunita Agrawal",
    email: "sunita@pithampurhr.org",
    phone: "+91 98270 99999",
    status: "Active",
    verificationsCount: 445,
    subscriptionType: "Professional",
    createdAt: "2024-06-01",
    lastActive: "2024-12-07",
  },
  {
    id: 5,
    organizationName: "Madhya Pradesh Police Department",
    contactPerson: "Inspector Vijay Tiwari",
    email: "vijay.tiwari@mppolice.gov.in",
    phone: "+91 98270 10101",
    status: "Active",
    verificationsCount: 678,
    subscriptionType: "Professional",
    createdAt: "2024-06-10",
    lastActive: "2024-12-06",
  },
];

export const mockPendingApprovals = [
  {
    id: 1,
    institutionName:
      "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
    uploadedBy: "Ramesh Kumar Verma",
    uploadDate: "2024-12-05",
    recordCount: 425,
    type: "Bulk Upload",
    status: "Pending",
    fileName: "sgsits_btech_2024_batch.xlsx",
  },
  {
    id: 2,
    institutionName: "Lakshmi Narain College of Technology (LNCT)",
    uploadedBy: "Pradeep Gupta",
    uploadDate: "2024-12-06",
    recordCount: 680,
    type: "Bulk Upload",
    status: "Pending",
    fileName: "lnct_students_semester5.csv",
  },
  {
    id: 3,
    institutionName: "Government Holkar Science College",
    uploadedBy: "Meena Joshi",
    uploadDate: "2024-12-06",
    recordCount: 315,
    type: "Bulk Upload",
    status: "Pending",
    fileName: "holkar_msc_students_2024.xlsx",
  },
  {
    id: 4,
    institutionName: "Madhav Institute of Technology and Science (MITS)",
    uploadedBy: "Suresh Patel",
    uploadDate: "2024-12-07",
    recordCount: 520,
    type: "Bulk Upload",
    status: "Pending",
    fileName: "mits_engineering_records.csv",
  },
];

export const mockCorrectionRequests = [
  {
    id: 1,
    studentName: "Amit Kumar Sharma",
    rollNumber: "RGPV20240001",
    institutionName:
      "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
    requestType: "Name Correction",
    oldValue: "Amit Sharna",
    newValue: "Amit Kumar Sharma",
    status: "Pending",
    requestDate: "2024-12-05",
    documents: ["aadhar_card.pdf", "birth_certificate.pdf"],
  },
  {
    id: 2,
    studentName: "Priya Rajput",
    rollNumber: "DAVV20230145",
    institutionName: "Government Holkar Science College",
    requestType: "Marks Correction",
    oldValue: "Semester 4: 68%",
    newValue: "Semester 4: 78%",
    status: "Pending",
    requestDate: "2024-12-06",
    documents: ["revised_marksheet.pdf"],
  },
  {
    id: 3,
    studentName: "Rahul Verma",
    rollNumber: "RGPV20220356",
    institutionName: "Lakshmi Narain College of Technology (LNCT)",
    requestType: "DOB Correction",
    oldValue: "15-05-2001",
    newValue: "15-05-2002",
    status: "Pending",
    requestDate: "2024-12-06",
    documents: [
      "corrected_birth_certificate.pdf",
      "school_leaving_certificate.pdf",
    ],
  },
  {
    id: 4,
    studentName: "Kavita Patel",
    rollNumber: "JUG20230089",
    institutionName: "Madhav Institute of Technology and Science (MITS)",
    requestType: "Course Correction",
    oldValue: "B.Tech - Mechanical Engineering",
    newValue: "B.Tech - Computer Science Engineering",
    status: "Pending",
    requestDate: "2024-12-07",
    documents: ["branch_change_approval.pdf"],
  },
];

export const mockStudents = [
  {
    id: 1,
    rollNumber: "RGPV20240001",
    name: "Amit Kumar Sharma",
    dob: "2002-05-15",
    institutionName:
      "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
    program: "B.Tech Computer Science",
    enrollmentYear: 2024,
    status: "Active",
    verificationStatus: "Verified",
  },
  {
    id: 2,
    rollNumber: "DAVV20230145",
    name: "Priya Rajput",
    dob: "2003-08-22",
    institutionName: "Government Holkar Science College",
    program: "M.Sc Physics",
    enrollmentYear: 2023,
    status: "Active",
    verificationStatus: "Verified",
  },
  {
    id: 3,
    rollNumber: "RGPV20220356",
    name: "Rahul Verma",
    dob: "2001-12-10",
    institutionName: "Lakshmi Narain College of Technology (LNCT)",
    program: "B.Tech Electronics & Communication",
    enrollmentYear: 2022,
    status: "Active",
    verificationStatus: "Verified",
  },
  {
    id: 4,
    rollNumber: "JUG20230089",
    name: "Kavita Patel",
    dob: "2002-03-18",
    institutionName: "Madhav Institute of Technology and Science (MITS)",
    program: "B.Tech Computer Science",
    enrollmentYear: 2023,
    status: "Active",
    verificationStatus: "Pending",
  },
  {
    id: 5,
    rollNumber: "DAVV20240567",
    name: "Rohan Singh Thakur",
    dob: "2003-11-05",
    institutionName: "Prestige Institute of Management and Research",
    program: "MBA Marketing",
    enrollmentYear: 2024,
    status: "Active",
    verificationStatus: "Verified",
  },
  {
    id: 6,
    rollNumber: "VUU20230234",
    name: "Sneha Agarwal",
    dob: "2002-07-28",
    institutionName: "Mahakal Institute of Technology",
    program: "B.Tech Mechanical Engineering",
    enrollmentYear: 2023,
    status: "Active",
    verificationStatus: "Verified",
  },
  {
    id: 7,
    rollNumber: "BUB20220445",
    name: "Vivek Dubey",
    dob: "2001-09-14",
    institutionName: "Government Holkar Science College",
    program: "B.Sc Mathematics",
    enrollmentYear: 2022,
    status: "Graduated",
    verificationStatus: "Verified",
  },
  {
    id: 8,
    rollNumber: "RGPV20240789",
    name: "Anjali Chouhan",
    dob: "2003-04-20",
    institutionName:
      "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)",
    program: "B.Tech Information Technology",
    enrollmentYear: 2024,
    status: "Active",
    verificationStatus: "Verified",
  },
];

export const mockAuditLogs = [
  {
    id: 1,
    timestamp: "2024-12-07 10:30:45",
    user: "Super Admin - Mriganka Shekhar Barman",
    action: "Approved Data Upload",
    details: "Approved 425 student records from SGSITS Indore",
    ipAddress: "103.25.45.100",
    status: "Success",
  },
  {
    id: 2,
    timestamp: "2024-12-07 09:15:22",
    user: "Ramesh Kumar Verma",
    action: "Bulk Upload",
    details: "Uploaded sgsits_btech_2024_batch.xlsx with 425 records",
    ipAddress: "103.25.45.50",
    status: "Success",
  },
  {
    id: 3,
    timestamp: "2024-12-06 16:45:10",
    user: "Infosys Limited",
    action: "Verification Request",
    details: "Verified student RollNo: RGPV20240001 from SGSITS",
    ipAddress: "203.45.67.89",
    status: "Success",
  },
  {
    id: 4,
    timestamp: "2024-12-06 14:20:35",
    user: "Super Admin - Mriganka Shekhar Barman",
    action: "Added University",
    details: "Added new university: IIT Indore",
    ipAddress: "103.25.45.100",
    status: "Success",
  },
  {
    id: 5,
    timestamp: "2024-12-06 11:55:18",
    user: "TCS (Tata Consultancy Services)",
    action: "Verification Request",
    details: "Verified student RollNo: DAVV20230145 from Holkar College",
    ipAddress: "202.88.99.45",
    status: "Success",
  },
  {
    id: 6,
    timestamp: "2024-12-06 10:10:50",
    user: "Pradeep Gupta",
    action: "Bulk Upload",
    details: "Uploaded lnct_students_semester5.csv with 680 records",
    ipAddress: "103.25.45.75",
    status: "Success",
  },
  {
    id: 7,
    timestamp: "2024-12-05 17:30:12",
    user: "Super Admin - Mriganka Shekhar Barman",
    action: "Approved Correction Request",
    details: "Approved name correction for student Amit Kumar Sharma",
    ipAddress: "103.25.45.100",
    status: "Success",
  },
  {
    id: 8,
    timestamp: "2024-12-05 15:45:30",
    user: "Madhya Pradesh Police Department",
    action: "Verification Request",
    details: "Verified student RollNo: RGPV20220356 from LNCT Bhopal",
    ipAddress: "103.12.34.56",
    status: "Success",
  },
];

export const dashboardStats = {
  totalUniversities: 8,
  totalInstitutions: 569,
  totalStudents: 1251650,
  totalVerifications: 67890,
  pendingApprovals: 4,
  activeTech: 89,
  monthlyGrowth: {
    universities: 12.5,
    institutions: 8.7,
    students: 15.3,
    verifications: 22.4,
  },
};
